import { Banner, Category, Product } from "@/types";

export const NAV_CATEGORIES: Category[] = [
  {
    id: "kadin",
    name: "Kadın Giyim",
    href: "/kadin",
    subCategories: [
      { name: "Üst Giyim", href: "/kadin/ust", items: ["Bluz", "T-Shirt", "Gömlek", "Kazak", "Hırka", "Yelek"] },
      { name: "Alt Giyim", href: "/kadin/alt", items: ["Jean", "Tayt", "Etek", "Şort", "Palazzo"] },
      { name: "Elbise & Tulum", href: "/kadin/elbise", items: ["Günlük Elbise", "Abiye", "Elbise Tulum"] },
      { name: "Dış Giyim", href: "/kadin/dis", items: ["Mont", "Kaban", "Trençkot", "Ceket", "Yağmurluk"] },
      { name: "Spor Giyim", href: "/kadin/spor", items: ["Tayt", "Spor Top", "Eşofman", "Spor Ceket"] },
    ],
    featured: [
      { name: "Zara", logo: "/brands/zara.png", href: "/brand/zara" },
      { name: "Mango", logo: "/brands/mango.png", href: "/brand/mango" },
      { name: "H&M", logo: "/brands/hm.png", href: "/brand/hm" },
    ],
  },
  {
    id: "erkek",
    name: "Erkek Giyim",
    href: "/erkek",
    subCategories: [
      { name: "Üst Giyim", href: "/erkek/ust", items: ["T-Shirt", "Gömlek", "Sweatshirt", "Kazak", "Polo"] },
      { name: "Alt Giyim", href: "/erkek/alt", items: ["Jean", "Chino", "Eşofman Altı", "Şort"] },
      { name: "Dış Giyim", href: "/erkek/dis", items: ["Mont", "Kaban", "Ceket", "Trençkot"] },
      { name: "Takım Elbise", href: "/erkek/takim", items: ["Takım Elbise", "Blazer", "Yelek", "Pantolon"] },
      { name: "Spor Giyim", href: "/erkek/spor", items: ["Spor Şort", "Eşofman", "Sıklet", "Koşu Kıyafeti"] },
    ],
    featured: [
      { name: "Nike", logo: "/brands/nike.png", href: "/brand/nike" },
      { name: "Adidas", logo: "/brands/adidas.png", href: "/brand/adidas" },
      { name: "Levi's", logo: "/brands/levis.png", href: "/brand/levis" },
    ],
  },
  {
    id: "elektronik",
    name: "Elektronik",
    href: "/elektronik",
    subCategories: [
      { name: "Telefon & Aksesuar", href: "/elektronik/telefon", items: ["Akıllı Telefon", "Kılıf", "Şarj Aleti", "Kablo", "Kulaklık"] },
      { name: "Bilgisayar", href: "/elektronik/bilgisayar", items: ["Laptop", "Masaüstü", "Tablet", "Monitör", "Klavye & Mouse"] },
      { name: "TV & Ses", href: "/elektronik/tv", items: ["Smart TV", "OLED TV", "Soundbar", "Bluetooth Hoparlör"] },
      { name: "Fotoğraf & Video", href: "/elektronik/foto", items: ["Dijital Fotoğraf Makinesi", "Aksiyon Kamera", "Drone", "Objektif"] },
      { name: "Giyilebilir Teknoloji", href: "/elektronik/giyilebilir", items: ["Akıllı Saat", "Spor Bileklik", "Kablosuz Kulaklık"] },
    ],
  },
  {
    id: "ev-yasam",
    name: "Ev & Yaşam",
    href: "/ev-yasam",
    subCategories: [
      { name: "Mobilya", href: "/ev/mobilya", items: ["Koltuk", "Yatak", "Masa", "Sandalye", "Raf"] },
      { name: "Ev Tekstili", href: "/ev/tekstil", items: ["Nevresim", "Yastık", "Battaniye", "Perde", "Havlu"] },
      { name: "Mutfak", href: "/ev/mutfak", items: ["Pişirme Gereçleri", "Tencere & Tava", "Kahve Makinesi", "Blender"] },
      { name: "Dekorasyon", href: "/ev/dekor", items: ["Tablo", "Vazo", "Mum", "Çiçek Saksı", "Ayna"] },
    ],
  },
  {
    id: "kozmetik",
    name: "Güzellik & Kozmetik",
    href: "/kozmetik",
    subCategories: [
      { name: "Makyaj", href: "/kozmetik/makyaj", items: ["Fondöten", "Ruj", "Maskara", "Far Paleti", "Allık"] },
      { name: "Cilt Bakımı", href: "/kozmetik/cilt", items: ["Nemlendirici", "Serum", "Güneş Kremi", "Yüz Yıkama", "Tonik"] },
      { name: "Saç Bakımı", href: "/kozmetik/sac", items: ["Şampuan", "Saç Maskesi", "Saç Yağı", "Fön Makinesi"] },
      { name: "Parfüm", href: "/kozmetik/parfum", items: ["Kadın Parfümü", "Erkek Parfümü", "Unisex", "Deodorant"] },
    ],
  },
  {
    id: "spor",
    name: "Spor & Outdoor",
    href: "/spor",
    subCategories: [
      { name: "Fitness & Gym", href: "/spor/fitness", items: ["Dambıl", "Yoga Matı", "Resistance Band", "Protein Tozu"] },
      { name: "Outdoor", href: "/spor/outdoor", items: ["Kamp Malzemeleri", "Trekking Ayakkabısı", "Çadır", "Sırt Çantası"] },
      { name: "Bisiklet", href: "/spor/bisiklet", items: ["Şehir Bisikleti", "Dağ Bisikleti", "E-Bisiklet", "Kask"] },
      { name: "Su Sporları", href: "/spor/su", items: ["Mayo", "Sörf", "Dalış", "Yüzme Gözlüğü"] },
    ],
  },
  {
    id: "anne-bebek",
    name: "Anne & Bebek",
    href: "/anne-bebek",
    subCategories: [
      { name: "Bebek Giyim", href: "/bebek/giyim", items: ["0-6 Ay", "6-12 Ay", "1-3 Yaş", "3-6 Yaş"] },
      { name: "Oyuncak", href: "/bebek/oyuncak", items: ["Eğitici Oyuncak", "Lego", "Peluş", "Araba & Araçlar"] },
      { name: "Bebek Arabası", href: "/bebek/araba", items: ["Puset", "Travel Sistem", "Jogging"] },
      { name: "Mama & Bakım", href: "/bebek/bakım", items: ["Mama Sandalyesi", "Emzirme", "Banyo", "Bez"] },
    ],
  },
  {
    id: "gida",
    name: "Gıda & Market",
    href: "/gida",
    subCategories: [
      { name: "Atıştırmalık", href: "/gida/atistirmalik", items: ["Çikolata", "Bisküvi", "Kuruyemiş", "Cips"] },
      { name: "İçecek", href: "/gida/icecek", items: ["Kahve", "Çay", "Meyve Suyu", "Enerji İçeceği"] },
      { name: "Organik & Doğal", href: "/gida/organik", items: ["Organik Tahıl", "Bakliyat", "Honey", "Zeytinyağı"] },
    ],
  },
];

export const HERO_BANNERS: Banner[] = [
  {
    id: "1",
    image: "https://picsum.photos/seed/tmall1/1200/400",
    title: "Yaz Koleksiyonu %70'e Varan İndirim",
    subtitle: "Sezon sonu fırsatlarını kaçırma",
    href: "/kampanya/yaz",
    bgColor: "#FF0036",
  },
  {
    id: "2",
    image: "https://picsum.photos/seed/tmall2/1200/400",
    title: "Elektronik Günleri",
    subtitle: "Telefon, bilgisayar, tablet fırsatları",
    href: "/kampanya/elektronik",
    bgColor: "#1A1A2E",
  },
  {
    id: "3",
    image: "https://picsum.photos/seed/tmall3/1200/400",
    title: "Ev & Mobilya Festivali",
    subtitle: "Evinizi yenileyin, ödemeyi sonra yapın",
    href: "/kampanya/ev",
    bgColor: "#2D6A4F",
  },
  {
    id: "4",
    image: "https://picsum.photos/seed/tmall4/1200/400",
    title: "Güzellik Dünyası",
    subtitle: "Orijinal markalar, uygun fiyatlar",
    href: "/kampanya/kozmetik",
    bgColor: "#9B2335",
  },
];

export const FLASH_PRODUCTS: Product[] = [
  {
    id: "f1",
    name: "Apple iPhone 15 Pro 256GB Doğal Titanyum",
    image: "https://picsum.photos/seed/iphone15/300/300",
    price: 52999,
    originalPrice: 64999,
    discount: 18,
    shop: "Apple Türkiye",
    sold: 1243,
    rating: 4.9,
    isFlash: true,
    badge: "ÇOK SATILAN",
  },
  {
    id: "f2",
    name: "Samsung Galaxy S24 Ultra 512GB",
    image: "https://picsum.photos/seed/samsung24/300/300",
    price: 44999,
    originalPrice: 59999,
    discount: 25,
    shop: "Samsung Resmi Mağaza",
    sold: 876,
    rating: 4.8,
    isFlash: true,
  },
  {
    id: "f3",
    name: "Sony WH-1000XM5 Gürültü Engelleyici Kulaklık",
    image: "https://picsum.photos/seed/sony/300/300",
    price: 8499,
    originalPrice: 12999,
    discount: 35,
    shop: "Sony Türkiye",
    sold: 2341,
    rating: 4.9,
    isFlash: true,
    badge: "TÜKENİYOR",
  },
  {
    id: "f4",
    name: "Dyson V15 Detect Absolute Süpürge",
    image: "https://picsum.photos/seed/dyson/300/300",
    price: 18999,
    originalPrice: 24999,
    discount: 24,
    shop: "Dyson Resmi",
    sold: 432,
    rating: 4.7,
    isFlash: true,
  },
  {
    id: "f5",
    name: "Nike Air Max 270 Erkek Spor Ayakkabı",
    image: "https://picsum.photos/seed/nikeair/300/300",
    price: 2499,
    originalPrice: 4299,
    discount: 42,
    shop: "Nike Türkiye",
    sold: 5621,
    rating: 4.6,
    isFlash: true,
    badge: "EN ÇOK SATAN",
  },
  {
    id: "f6",
    name: "LEGO Technic Bugatti Chiron 42083",
    image: "https://picsum.photos/seed/lego/300/300",
    price: 7499,
    originalPrice: 9999,
    discount: 25,
    shop: "LEGO Resmi Mağaza",
    sold: 321,
    rating: 4.9,
    isFlash: true,
  },
];

export const FEATURED_PRODUCTS: Product[] = [
  {
    id: "p1",
    name: "MacBook Pro 14 M3 Pro Çip 18GB RAM 512GB SSD",
    image: "https://picsum.photos/seed/macbook/300/300",
    price: 79999,
    originalPrice: 89999,
    discount: 11,
    shop: "Apple Türkiye",
    sold: 234,
    rating: 4.9,
  },
  {
    id: "p2",
    name: "Zara Kadın Oversize Blazer Ceket",
    image: "https://picsum.photos/seed/zara1/300/300",
    price: 899,
    originalPrice: 1499,
    discount: 40,
    shop: "Zara Türkiye",
    sold: 1832,
    rating: 4.5,
  },
  {
    id: "p3",
    name: "De'Longhi Dedica Style Espresso Makinesi",
    image: "https://picsum.photos/seed/delonghi/300/300",
    price: 6499,
    originalPrice: 8499,
    discount: 24,
    shop: "De'Longhi Resmi",
    sold: 892,
    rating: 4.7,
  },
  {
    id: "p4",
    name: "Philips Hue Akıllı LED Ampul Starter Pack",
    image: "https://picsum.photos/seed/philips/300/300",
    price: 1299,
    originalPrice: 1799,
    discount: 28,
    shop: "Philips Türkiye",
    sold: 2341,
    rating: 4.6,
  },
];

export const QUICK_CATEGORIES = [
  { name: "Kadın Giyim", icon: "👗", href: "/kadin", color: "#FF6B9D" },
  { name: "Erkek Giyim", icon: "👔", href: "/erkek", color: "#4A90D9" },
  { name: "Elektronik", icon: "📱", href: "/elektronik", color: "#FF6000" },
  { name: "Ev & Yaşam", icon: "🏠", href: "/ev-yasam", color: "#52C41A" },
  { name: "Güzellik", icon: "💄", href: "/kozmetik", color: "#EB2F96" },
  { name: "Spor", icon: "⚽", href: "/spor", color: "#1890FF" },
  { name: "Anne & Bebek", icon: "🍼", href: "/anne-bebek", color: "#FAAD14" },
  { name: "Gıda", icon: "🛒", href: "/gida", color: "#13C2C2" },
  { name: "Kitap", icon: "📚", href: "/kitap", color: "#722ED1" },
  { name: "Oyun", icon: "🎮", href: "/oyun", color: "#F5222D" },
];
