import { Product, Brand } from "@/types";

export const ALL_PRODUCTS: Product[] = [
  // ── ELEKTRONİK ─────────────────────────────────────────────
  {
    id: "e1",
    name: "Apple iPhone 15 Pro 256GB Doğal Titanyum",
    image: "https://picsum.photos/seed/iphone15p/400/400",
    images: [
      "https://picsum.photos/seed/iphone15p/600/600",
      "https://picsum.photos/seed/iphone15p2/600/600",
      "https://picsum.photos/seed/iphone15p3/600/600",
    ],
    price: 52999,
    originalPrice: 64999,
    discount: 18,
    shop: "Apple Türkiye Resmi",
    sold: 1243,
    rating: 4.9,
    ratingCount: 3872,
    category: "elektronik",
    brand: "apple",
    badge: "ÇOK SATILAN",
    description:
      "Apple iPhone 15 Pro, A17 Pro çipiyle güçlendirilmiş sektörün en hızlı mobil işlemcisine sahip. Titanyum gövdesi hafifliği ve dayanıklılığı bir arada sunarken, 48MP ana kamera sistemi fotoğrafçılığı yeniden tanımlıyor.",
    stock: 45,
    variants: [
      { name: "Renk", options: ["Doğal Titanyum", "Mavi Titanyum", "Siyah Titanyum", "Beyaz Titanyum"] },
      { name: "Kapasite", options: ["128GB", "256GB", "512GB", "1TB"] },
    ],
    isFlash: false,
  },
  {
    id: "e2",
    name: "Samsung Galaxy S24 Ultra 512GB Phantom Black",
    image: "https://picsum.photos/seed/s24ultra/400/400",
    images: [
      "https://picsum.photos/seed/s24ultra/600/600",
      "https://picsum.photos/seed/s24ultra2/600/600",
    ],
    price: 44999,
    originalPrice: 59999,
    discount: 25,
    shop: "Samsung Resmi Mağaza",
    sold: 876,
    rating: 4.8,
    ratingCount: 2341,
    category: "elektronik",
    brand: "samsung",
    description:
      "Galaxy S24 Ultra, 200MP kamera ve dahili S Pen ile yaratıcılığınızı en üst seviyeye taşır. Yapay zeka destekli Galaxy AI özellikleritüm iletişim ve üretkenlik ihtiyaçlarınızı karşılar.",
    stock: 28,
    variants: [
      { name: "Renk", options: ["Phantom Black", "Titanium Gray", "Titanium Violet", "Titanium Yellow"] },
      { name: "Kapasite", options: ["256GB", "512GB", "1TB"] },
    ],
  },
  {
    id: "e3",
    name: "Sony WH-1000XM5 Gürültü Engelleyici Bluetooth Kulaklık",
    image: "https://picsum.photos/seed/sonywh/400/400",
    images: [
      "https://picsum.photos/seed/sonywh/600/600",
      "https://picsum.photos/seed/sonywh2/600/600",
    ],
    price: 8499,
    originalPrice: 12999,
    discount: 35,
    shop: "Sony Türkiye",
    sold: 2341,
    rating: 4.9,
    ratingCount: 5120,
    category: "elektronik",
    brand: "sony",
    badge: "EN İYİ SEÇIM",
    description:
      "Sektör lideri gürültü engelleme teknolojisi ve 30 saate kadar pil ömrüyle WH-1000XM5, dinleme deneyimini başka bir boyuta taşıyor. LDAC ile Hi-Res Audio desteği.",
    stock: 67,
    variants: [
      { name: "Renk", options: ["Siyah", "Gümüş", "Gece Mavisi"] },
    ],
    isFlash: true,
  },
  {
    id: "e4",
    name: "Apple MacBook Pro 14\" M3 Pro 18GB/512GB",
    image: "https://picsum.photos/seed/macbookpro/400/400",
    images: [
      "https://picsum.photos/seed/macbookpro/600/600",
      "https://picsum.photos/seed/macbookpro2/600/600",
    ],
    price: 79999,
    originalPrice: 89999,
    discount: 11,
    shop: "Apple Türkiye Resmi",
    sold: 234,
    rating: 4.9,
    ratingCount: 891,
    category: "elektronik",
    brand: "apple",
    description:
      "M3 Pro çipiyle çalışan MacBook Pro 14\", profesyonel iş yüklerinde benzersiz performans sunar. Liquid Retina XDR ekran ve 22 saate kadar pil ömrüyle tam güç mobil çalışma.",
    stock: 12,
    variants: [
      { name: "Renk", options: ["Uzay Siyahı", "Gümüş"] },
      { name: "Konfigürasyon", options: ["M3 Pro 18GB/512GB", "M3 Pro 18GB/1TB", "M3 Max 36GB/1TB"] },
    ],
  },
  {
    id: "e5",
    name: "Apple iPad Air 11\" M2 256GB Wi-Fi + Cellular",
    image: "https://picsum.photos/seed/ipadair/400/400",
    price: 24999,
    originalPrice: 28999,
    discount: 14,
    shop: "Apple Türkiye Resmi",
    sold: 541,
    rating: 4.8,
    ratingCount: 1203,
    category: "elektronik",
    brand: "apple",
    description:
      "M2 çipli iPad Air, Apple Pencil Pro ve Magic Keyboard desteğiyle güçlü bir çalışma ve yaratıcılık aracıdır.",
    stock: 34,
    variants: [
      { name: "Renk", options: ["Mavi", "Mor", "Yıldız Işığı", "Uzay Grisi"] },
      { name: "Kapasite", options: ["128GB", "256GB"] },
    ],
  },
  {
    id: "e6",
    name: "Sony PlayStation 5 Slim Oyun Konsolu",
    image: "https://picsum.photos/seed/ps5slim/400/400",
    price: 19999,
    originalPrice: 24999,
    discount: 20,
    shop: "Sony Türkiye",
    sold: 3421,
    rating: 4.9,
    ratingCount: 8901,
    category: "elektronik",
    brand: "sony",
    badge: "STOK TÜKENIYOR",
    description:
      "PlayStation 5 Slim, önceki nesle göre %30 daha kompakt tasarımı ve 1TB SSD depolama alanıyla sizi yeni nesil oyun dünyasına taşır.",
    stock: 8,
    isFlash: true,
  },
  {
    id: "e7",
    name: "Samsung 65\" OLED 4K Smart TV QN65S95D",
    image: "https://picsum.photos/seed/samsungtv/400/400",
    price: 54999,
    originalPrice: 74999,
    discount: 27,
    shop: "Samsung Resmi Mağaza",
    sold: 189,
    rating: 4.7,
    ratingCount: 412,
    category: "elektronik",
    brand: "samsung",
    description:
      "QD-OLED teknolojisi ile mükemmel siyahlar ve canlı renkler. Tizen OS ve gaming odası modu ile PC ve konsol oyunu deneyimini maksimize eder.",
    stock: 15,
    variants: [
      { name: "Ekran Boyutu", options: ["55\"", "65\"", "77\""] },
    ],
  },
  {
    id: "e8",
    name: "Apple AirPods Pro (2. Nesil) USB-C",
    image: "https://picsum.photos/seed/airpodspro/400/400",
    price: 8999,
    originalPrice: 10999,
    discount: 18,
    shop: "Apple Türkiye Resmi",
    sold: 4521,
    rating: 4.8,
    ratingCount: 9234,
    category: "elektronik",
    brand: "apple",
    description:
      "H2 çip, Uyarlanabilir Ses Şeffaflığı ve Kişiselleştirilmiş Mekansal Ses ile AirPods Pro deneyimini yeniden tanımlıyor.",
    stock: 89,
    isFlash: true,
  },

  // ── KADIN GİYİM ────────────────────────────────────────────
  {
    id: "k1",
    name: "Zara Kadın Oversize Yün Blazer Ceket",
    image: "https://picsum.photos/seed/zarablazer/400/400",
    images: [
      "https://picsum.photos/seed/zarablazer/600/600",
      "https://picsum.photos/seed/zarablazer2/600/600",
    ],
    price: 1299,
    originalPrice: 2199,
    discount: 41,
    shop: "Zara Türkiye",
    sold: 2341,
    rating: 4.6,
    ratingCount: 3201,
    category: "kadin",
    brand: "zara",
    description:
      "Modern kesimi ve premium yün karışımı kumaşıyla Oversize Blazer, casual ve formal kombinlerin vazgeçilmezi. Yan cepleri ve yapılandırılmış omuz detayıyla şık bir siluet sunar.",
    stock: 87,
    variants: [
      { name: "Renk", options: ["Camel", "Siyah", "Ekru", "Lacivert"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL"] },
    ],
  },
  {
    id: "k2",
    name: "Mango Kadın Midi Saten Etek",
    image: "https://picsum.photos/seed/mangoetek/400/400",
    price: 799,
    originalPrice: 1299,
    discount: 38,
    shop: "Mango Türkiye",
    sold: 1823,
    rating: 4.5,
    ratingCount: 2107,
    category: "kadin",
    brand: "mango",
    description:
      "Saten dokusu ve midi boyu ile zarif görünümler için ideal. Elastik bel bantıyla rahat kullanım.",
    stock: 64,
    variants: [
      { name: "Renk", options: ["Siyah", "Kırmızı", "Yeşil", "Bej"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL"] },
    ],
  },
  {
    id: "k3",
    name: "H&M Kadın Oversize Pamuklu Sweatshirt",
    image: "https://picsum.photos/seed/hmsweat/400/400",
    price: 349,
    originalPrice: 599,
    discount: 42,
    shop: "H&M Türkiye",
    sold: 5621,
    rating: 4.4,
    ratingCount: 8902,
    category: "kadin",
    brand: "hm",
    badge: "EN ÇOK SATAN",
    description:
      "Yumuşak pamuk karışımı kumaşıyla günlük kullanım için tasarlanmış oversize sweatshirt. Dropped shoulder detayı modern bir görünüm sağlar.",
    stock: 234,
    variants: [
      { name: "Renk", options: ["Gri Melanj", "Siyah", "Ekru", "Toz Pembe", "Sage"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL", "XXL"] },
    ],
    isFlash: true,
  },
  {
    id: "k4",
    name: "Zara Kadın Yüksek Bel Skinny Jean",
    image: "https://picsum.photos/seed/zarajean/400/400",
    price: 899,
    originalPrice: 1499,
    discount: 40,
    shop: "Zara Türkiye",
    sold: 3241,
    rating: 4.7,
    ratingCount: 4521,
    category: "kadin",
    brand: "zara",
    description:
      "Yüksek bel kesimi ve skinny fit siluetiyle her vücut tipine uygun. %2 Elastan içeriği sayesinde tam hareket özgürlüğü.",
    stock: 156,
    variants: [
      { name: "Renk", options: ["Koyu Mavi", "Açık Mavi", "Siyah", "Beyaz"] },
      { name: "Beden", options: ["34", "36", "38", "40", "42", "44"] },
    ],
  },
  {
    id: "k5",
    name: "Mango Kadın Yazlık Floral Maxi Elbise",
    image: "https://picsum.photos/seed/mangodress/400/400",
    price: 1099,
    originalPrice: 1799,
    discount: 39,
    shop: "Mango Türkiye",
    sold: 987,
    rating: 4.6,
    ratingCount: 1234,
    category: "kadin",
    brand: "mango",
    description:
      "Çiçek baskılı şifon kumaşı ve maxi boyu ile yaz aylarının vazgeçilmez parçası. İnce askıları ve V yaka detayıyla feminen bir görünüm.",
    stock: 43,
    variants: [
      { name: "Renk", options: ["Beyaz Floral", "Mavi Floral", "Sarı Floral"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL"] },
    ],
    isFlash: true,
  },
  {
    id: "k6",
    name: "H&M Kadın Keten Yüksek Bel Palazzo Pantolon",
    image: "https://picsum.photos/seed/hmpant/400/400",
    price: 499,
    originalPrice: 849,
    discount: 41,
    shop: "H&M Türkiye",
    sold: 2109,
    rating: 4.5,
    ratingCount: 3012,
    category: "kadin",
    brand: "hm",
    description:
      "Nefes alan keten kumaşı ve geniş paçasıyla yazın en rahat seçeneği. Elastik bel bantıyla kolay giyim.",
    stock: 112,
    variants: [
      { name: "Renk", options: ["Krem", "Haki", "Siyah", "Terracotta"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL"] },
    ],
  },

  // ── ERKEK GİYİM ────────────────────────────────────────────
  {
    id: "r1",
    name: "Nike Erkek Sportswear Club Fleece Hoodie",
    image: "https://picsum.photos/seed/nikehoodie/400/400",
    price: 1299,
    originalPrice: 1899,
    discount: 32,
    shop: "Nike Türkiye",
    sold: 4521,
    rating: 4.7,
    ratingCount: 6723,
    category: "erkek",
    brand: "nike",
    description:
      "Yumuşak, ağır French terry kumaşıyla sizi sıcak tutar. Kanguru cebi ve çekilebilir kapüşon ile tamamlanmış ikonik Nike tasarımı.",
    stock: 178,
    variants: [
      { name: "Renk", options: ["Siyah", "Gri", "Lacivert", "Bordo", "Yeşil"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL", "2XL", "3XL"] },
    ],
    isFlash: true,
  },
  {
    id: "r2",
    name: "Adidas Originals Erkek Trefoil Hoodie",
    image: "https://picsum.photos/seed/adidashoodie/400/400",
    price: 1099,
    originalPrice: 1699,
    discount: 35,
    shop: "Adidas Türkiye",
    sold: 3201,
    rating: 4.6,
    ratingCount: 4512,
    category: "erkek",
    brand: "adidas",
    description:
      "Adidas'ın ikonik Trefoil logosuyla bezeli klasik hoodie. Ağır polar kumaşı ve geniş kesimi ile şehir hayatının vazgeçilmezi.",
    stock: 134,
    variants: [
      { name: "Renk", options: ["Siyah/Beyaz", "Gri", "Lacivert", "Yeşil"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL", "2XL"] },
    ],
  },
  {
    id: "r3",
    name: "Levi's 511 Slim Fit Erkek Jean",
    image: "https://picsum.photos/seed/levisjean/400/400",
    price: 1199,
    originalPrice: 1799,
    discount: 33,
    shop: "Levi's Türkiye",
    sold: 6712,
    rating: 4.8,
    ratingCount: 9823,
    category: "erkek",
    brand: "levis",
    badge: "EN ÇOK SATAN",
    description:
      "Levi's 511, diz altından baldıra kadar dar kesimi ve esnek denim kumaşıyla modern erkeğin ideal günlük pantolonu.",
    stock: 312,
    variants: [
      { name: "Renk", options: ["Koyu Indigo", "Orta Mavi", "Siyah", "Gri"] },
      { name: "Beden", options: ["28x30", "30x32", "32x32", "34x32", "34x34", "36x32"] },
    ],
  },
  {
    id: "r4",
    name: "Nike Erkek Dri-FIT Polo Gömlek",
    image: "https://picsum.photos/seed/nikepolo/400/400",
    price: 799,
    originalPrice: 1299,
    discount: 38,
    shop: "Nike Türkiye",
    sold: 2341,
    rating: 4.5,
    ratingCount: 3120,
    category: "erkek",
    brand: "nike",
    description:
      "Dri-FIT teknolojisiyle nemi uzaklaştıran kumaşı, hareket kısıtlamayan kesimi ile spor ve casual kullanım için ideal.",
    stock: 89,
    variants: [
      { name: "Renk", options: ["Beyaz", "Siyah", "Lacivert", "Kırmızı"] },
      { name: "Beden", options: ["S", "M", "L", "XL", "2XL"] },
    ],
  },
  {
    id: "r5",
    name: "Adidas Erkek Hafif Rüzgarlık Mont",
    image: "https://picsum.photos/seed/adidasmont/400/400",
    price: 1799,
    originalPrice: 2799,
    discount: 36,
    shop: "Adidas Türkiye",
    sold: 1234,
    rating: 4.6,
    ratingCount: 1892,
    category: "erkek",
    brand: "adidas",
    description:
      "100% geri dönüştürülmüş malzemeden üretilmiş, hafif ve rüzgar geçirmez yapısıyla dört mevsim geçiş kıyafeti.",
    stock: 67,
    variants: [
      { name: "Renk", options: ["Siyah", "Lacivert", "Haki", "Kırmızı"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL", "2XL"] },
    ],
  },
  {
    id: "r6",
    name: "Levi's Erkek Vintage Trucker Denim Ceket",
    image: "https://picsum.photos/seed/leviscoat/400/400",
    price: 1699,
    originalPrice: 2499,
    discount: 32,
    shop: "Levi's Türkiye",
    sold: 892,
    rating: 4.7,
    ratingCount: 1234,
    category: "erkek",
    brand: "levis",
    description:
      "Levi's'in ikonik Trucker modelinin vintage işlemeli versiyonu. Klasik denim kumaşı ve dökümlü kesim ile zamanı aşan bir parça.",
    stock: 45,
    variants: [
      { name: "Renk", options: ["Indigo Mavi", "Siyah", "Açık Mavi"] },
      { name: "Beden", options: ["S", "M", "L", "XL", "2XL"] },
    ],
  },

  // ── EV & YAŞAM ─────────────────────────────────────────────
  {
    id: "v1",
    name: "Dyson V15 Detect Absolute Kablosuz Süpürge",
    image: "https://picsum.photos/seed/dysonv15/400/400",
    images: [
      "https://picsum.photos/seed/dysonv15/600/600",
      "https://picsum.photos/seed/dysonv15b/600/600",
    ],
    price: 18999,
    originalPrice: 24999,
    discount: 24,
    shop: "Dyson Resmi Türkiye",
    sold: 1234,
    rating: 4.9,
    ratingCount: 2341,
    category: "ev-yasam",
    brand: "dyson",
    description:
      "Lazer tozlanma algılama, HEPA filtre ve 60 dakika pil ömrüyle V15 Detect, ev temizliğinde devrim niteliğinde. Piezo sensör tozu sayarak tarama etkinliğini gerçek zamanlı raporlar.",
    stock: 23,
    variants: [
      { name: "Aksesuar", options: ["Absolute", "Extra", "Complete"] },
    ],
    isFlash: true,
  },
  {
    id: "v2",
    name: "De'Longhi Dedica Style EC685 Espresso Makinesi",
    image: "https://picsum.photos/seed/delonghiec/400/400",
    price: 6499,
    originalPrice: 8499,
    discount: 24,
    shop: "De'Longhi Resmi",
    sold: 1892,
    rating: 4.7,
    ratingCount: 3012,
    category: "ev-yasam",
    brand: "delonghi",
    description:
      "Dedica Style, 15 bar basınç ve termoblock ısıtma teknolojisiyle 35 saniyede ısınarak barista kalitesinde espresso hazırlar. İnce tasarımıyla mutfak tezgahında minimum yer kaplar.",
    stock: 67,
    variants: [
      { name: "Renk", options: ["Paslanmaz Çelik", "Siyah", "Kırmızı"] },
    ],
  },
  {
    id: "v3",
    name: "Philips Hue White & Color Ambiance Başlangıç Seti",
    image: "https://picsum.photos/seed/philipshue/400/400",
    price: 2299,
    originalPrice: 2999,
    discount: 23,
    shop: "Philips Türkiye",
    sold: 3412,
    rating: 4.6,
    ratingCount: 5201,
    category: "ev-yasam",
    brand: "philips",
    description:
      "3 akıllı ampul ve Bridge dahil bu başlangıç seti ile evinizi 16 milyon renk ve binlerce beyaz ton arasından kişiselleştirin. Alexa, Google Home ve Apple HomeKit uyumlu.",
    stock: 134,
    variants: [
      { name: "Paket", options: ["3 Ampul + Bridge", "4 Ampul + Bridge", "Bridge + Güçlendirici"] },
    ],
  },
  {
    id: "v4",
    name: "IKEA EKTORP 3'lü Koltuk Takımı Beyaz",
    image: "https://picsum.photos/seed/ikeasofa/400/400",
    price: 8999,
    originalPrice: 12499,
    discount: 28,
    shop: "IKEA Türkiye",
    sold: 321,
    rating: 4.4,
    ratingCount: 512,
    category: "ev-yasam",
    brand: "ikea",
    description:
      "Çıkarılabilir ve yıkanabilir kılıfları, derin oturma derinliği ve sağlam iç çerçevesiyle EKTORP aile evleri için vazgeçilmez.",
    stock: 18,
    variants: [
      { name: "Renk/Kılıf", options: ["Beyaz", "Koyu Gri", "Bej", "Açık Mavi"] },
    ],
  },
  {
    id: "v5",
    name: "Dyson Airwrap Complete Saç Şekillendirici",
    image: "https://picsum.photos/seed/airwrap/400/400",
    price: 14999,
    originalPrice: 18999,
    discount: 21,
    shop: "Dyson Resmi Türkiye",
    sold: 2341,
    rating: 4.8,
    ratingCount: 4512,
    category: "ev-yasam",
    brand: "dyson",
    badge: "TREND",
    description:
      "Coanda etkisiyle saçı aşırı ısıya maruz bırakmadan şekillendiren Airwrap, fön, kıvırma ve düzleştirme işlemlerini tek cihazda birleştirir.",
    stock: 34,
    variants: [
      { name: "Set", options: ["Complete Long", "Complete", "Multi-Styler"] },
    ],
    isFlash: true,
  },
  {
    id: "v6",
    name: "Tefal Cook4Me+ Connect Çok Fonksiyonlu Pişirici 6L",
    image: "https://picsum.photos/seed/tefalpot/400/400",
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    shop: "Tefal Türkiye",
    sold: 892,
    rating: 4.5,
    ratingCount: 1234,
    category: "ev-yasam",
    brand: "tefal",
    description:
      "Bluetooth bağlantılı uygulama ile 250'den fazla tarife ve otomatik pişirme programlarıyla mutfakta zaman kazanın. Basınçlı pişirici, yavaş pişirici, kızartma, buharda pişirme.",
    stock: 45,
  },

  // ── GÜZELLİK & KOZMETİK ───────────────────────────────────
  {
    id: "g1",
    name: "Charlotte Tilbury Hollywood Flawless Filter 30ml",
    image: "https://picsum.photos/seed/ctfilter/400/400",
    price: 1299,
    originalPrice: 1699,
    discount: 24,
    shop: "Charlotte Tilbury Resmi",
    sold: 4521,
    rating: 4.8,
    ratingCount: 7234,
    category: "kozmetik",
    brand: "charlottetilbury",
    badge: "VIRAL",
    description:
      "Işıltılı, dolgun görünümlü bir cilt için primer, aydınlatıcı ve renk düzenleyiciyi tek ürünle birleştiren Charlotte Tilbury'nin en çok sevilen ürünü.",
    stock: 89,
    variants: [
      { name: "Ton", options: ["1 Fair", "2 Light", "3 Light Medium", "4 Medium", "5 Medium Deep", "6 Deep"] },
    ],
    isFlash: true,
  },
  {
    id: "g2",
    name: "Dior Rouge Dior Satin Ruj",
    image: "https://picsum.photos/seed/diorruj/400/400",
    price: 1799,
    originalPrice: 2199,
    discount: 18,
    shop: "Dior Beauty Türkiye",
    sold: 2341,
    rating: 4.7,
    ratingCount: 3201,
    category: "kozmetik",
    brand: "dior",
    description:
      "Nemlendirici formülü ve zengin satin dokusuyla dudakları besleyen ve renklendiren Dior Rouge Dior, ikonlar arasındaki yerini korumaya devam ediyor.",
    stock: 67,
    variants: [
      { name: "Renk", options: ["999 Rouge", "Rose Montaigne", "Beige Mitzah", "Ultra Rouge"] },
    ],
  },
  {
    id: "g3",
    name: "CeraVe Nemlendirici Krem 454g",
    image: "https://picsum.photos/seed/cerave/400/400",
    price: 549,
    originalPrice: 749,
    discount: 27,
    shop: "CeraVe Türkiye",
    sold: 12341,
    rating: 4.9,
    ratingCount: 24512,
    category: "kozmetik",
    brand: "cerave",
    badge: "DERMATOLOG ÖNERİLİ",
    description:
      "Seramid, hyaluronik asit ve niasinamid içeren formülüyle cilt bariyerini onaran ve 24 saat nemlendiren tıbbi cilt bakım kremine dermatologların güveni.",
    stock: 456,
    isFlash: true,
  },
  {
    id: "g4",
    name: "Fenty Beauty Pro Filt'r Soft Matte Fondöten",
    image: "https://picsum.photos/seed/fentybeauty/400/400",
    price: 1599,
    originalPrice: 1999,
    discount: 20,
    shop: "Fenty Beauty Türkiye",
    sold: 3412,
    rating: 4.7,
    ratingCount: 5123,
    category: "kozmetik",
    brand: "fenty",
    description:
      "50 ton seçeneği ve 24 saat kalıcı soft-matte finişiyle Pro Filt'r, her cilt tonu için kusursuz kaplama sunar. Sebum kontrolü için formüle edilmiştir.",
    stock: 123,
    variants: [
      { name: "Ton", options: ["100W", "130N", "185W", "240N", "300W", "370N", "450W", "495N"] },
    ],
  },
  {
    id: "g5",
    name: "The Ordinary Niacinamide 10% + Zinc 1% Serum 30ml",
    image: "https://picsum.photos/seed/theordinary/400/400",
    price: 349,
    originalPrice: 499,
    discount: 30,
    shop: "DECIEM Türkiye",
    sold: 18923,
    rating: 4.8,
    ratingCount: 32145,
    category: "kozmetik",
    brand: "theordinary",
    description:
      "Gözenek görünümünü azaltan, yağ dengesini düzenleyen ve cilt tonunu eşitleyen çok satan serum. Sebum üretimini kontrol eder ve leke görünümünü azaltır.",
    stock: 890,
  },
  {
    id: "g6",
    name: "Benefit Cosmetics Badgal Bang Maskara",
    image: "https://picsum.photos/seed/benefit/400/400",
    price: 899,
    originalPrice: 1199,
    discount: 25,
    shop: "Benefit Cosmetics Türkiye",
    sold: 5123,
    rating: 4.6,
    ratingCount: 8234,
    category: "kozmetik",
    brand: "benefit",
    description:
      "Patentli 36 saatlik kalıcı formülü ve büyük kıvrımlandırıcı fırçasıyla kirpikleri dramatik şekilde uzatır ve kıvırır.",
    stock: 234,
  },

  // ── SPOR & OUTDOOR ─────────────────────────────────────────
  {
    id: "s1",
    name: "Nike Air Max 270 Erkek Spor Ayakkabı",
    image: "https://picsum.photos/seed/nikeam270/400/400",
    images: [
      "https://picsum.photos/seed/nikeam270/600/600",
      "https://picsum.photos/seed/nikeam270b/600/600",
    ],
    price: 2499,
    originalPrice: 4299,
    discount: 42,
    shop: "Nike Türkiye",
    sold: 5621,
    rating: 4.6,
    ratingCount: 8923,
    category: "spor",
    brand: "nike",
    badge: "EN ÇOK SATAN",
    description:
      "Nike Air Max tarihinin en büyük arka Air ünitesine sahip 270, günlük konfor ve ikonik stil için tasarlandı. Streç örgü üst ve hafif EVA taban ile serbest hissettiren bir yapı.",
    stock: 234,
    variants: [
      { name: "Renk", options: ["Siyah/Beyaz", "Beyaz/Mavi", "Siyah/Kırmızı", "Triple Siyah"] },
      { name: "Numara", options: ["40", "40.5", "41", "42", "42.5", "43", "44", "44.5", "45", "46"] },
    ],
    isFlash: true,
  },
  {
    id: "s2",
    name: "Adidas Ultraboost 22 Koşu Ayakkabısı",
    image: "https://picsum.photos/seed/adidasub/400/400",
    price: 3499,
    originalPrice: 5499,
    discount: 36,
    shop: "Adidas Türkiye",
    sold: 2341,
    rating: 4.8,
    ratingCount: 4123,
    category: "spor",
    brand: "adidas",
    description:
      "BOOST tabanlı enerji geri kazanımı ve Primeknit+ üst ile koşularda üstün konfor. Her adımda amortize ederek enerjiyi geri kazandırır.",
    stock: 89,
    variants: [
      { name: "Renk", options: ["Siyah", "Beyaz/Kırmızı", "Lacivert"] },
      { name: "Numara", options: ["40", "41", "42", "43", "44", "45", "46"] },
    ],
  },
  {
    id: "s3",
    name: "Nike Kadın Pro Yüksek Bel Taytı",
    image: "https://picsum.photos/seed/niketayt/400/400",
    price: 799,
    originalPrice: 1299,
    discount: 38,
    shop: "Nike Türkiye",
    sold: 7823,
    rating: 4.7,
    ratingCount: 12341,
    category: "spor",
    brand: "nike",
    badge: "ÇOK SATILAN",
    description:
      "Dri-FIT teknolojisi ve yüksek bel tasarımıyla antrenmanda maksimum destek ve rahatlık. Opaklık için tasarlanmış şekillendirici kumaş.",
    stock: 456,
    variants: [
      { name: "Renk", options: ["Siyah", "Gri", "Lacivert", "Mor", "Yeşil"] },
      { name: "Beden", options: ["XS", "S", "M", "L", "XL"] },
    ],
  },
  {
    id: "s4",
    name: "LEGO Technic Bugatti Chiron 42083 (3599 parça)",
    image: "https://picsum.photos/seed/legobugatti/400/400",
    price: 7499,
    originalPrice: 9999,
    discount: 25,
    shop: "LEGO Resmi Mağaza",
    sold: 1234,
    rating: 4.9,
    ratingCount: 2341,
    category: "spor",
    brand: "lego",
    description:
      "3599 parçadan oluşan Bugatti Chiron seti, çalışan W16 motor, ayarlanabilir arka kanat ve gerçek araçta bulunan robotik valiz ile mükemmel bir koleksiyon parçası.",
    stock: 45,
  },
  {
    id: "s5",
    name: "Adidas X Speedportal.1 FG Krampon",
    image: "https://picsum.photos/seed/adidaskrampon/400/400",
    price: 2999,
    originalPrice: 4499,
    discount: 33,
    shop: "Adidas Türkiye",
    sold: 892,
    rating: 4.7,
    ratingCount: 1234,
    category: "spor",
    brand: "adidas",
    description:
      "Speedskin dış yüzeyi ve FG tabanıyla doğal çimen için tasarlanmış X Speedportal.1, hız tutkunları için optimize edilmiştir.",
    stock: 67,
    variants: [
      { name: "Renk", options: ["Siyah/Altın", "Solar Blue/Pink", "Core Black"] },
      { name: "Numara", options: ["40", "41", "42", "43", "44", "45"] },
    ],
  },
  {
    id: "s6",
    name: "Nike Revolution 6 Erkek Koşu Ayakkabısı",
    image: "https://picsum.photos/seed/nikerev6/400/400",
    price: 1299,
    originalPrice: 1899,
    discount: 32,
    shop: "Nike Türkiye",
    sold: 6712,
    rating: 4.5,
    ratingCount: 9823,
    category: "spor",
    brand: "nike",
    description:
      "Hafif ağırlıkta ve esnek yapısıyla günlük koşular için ideal giriş seviyesi koşu ayakkabısı. Pedleme bantlı üst ve yumuşak köpük taban.",
    stock: 312,
    variants: [
      { name: "Renk", options: ["Siyah/Beyaz", "Beyaz/Mavi", "Kırmızı/Siyah"] },
      { name: "Numara", options: ["40", "41", "42", "43", "44", "45", "46"] },
    ],
  },

  // ── ANNE & BEBEK ───────────────────────────────────────────
  {
    id: "b1",
    name: "Bugaboo Fox 5 Complete Travel System",
    image: "https://picsum.photos/seed/bugaboo/400/400",
    price: 32999,
    originalPrice: 42999,
    discount: 23,
    shop: "Bugaboo Türkiye",
    sold: 234,
    rating: 4.8,
    ratingCount: 512,
    category: "anne-bebek",
    brand: "bugaboo",
    description:
      "Doğumdan 4 yaşına kadar kullanılabilen Fox 5, tüm zeminlerde mükemmel sürüş konforu sunar. Anakucak, oturma ünitesi ve güneşlik dahil komple set.",
    stock: 12,
    variants: [
      { name: "Renk", options: ["Siyah", "Gri", "Bordo", "Orman Yeşili"] },
    ],
  },
  {
    id: "b2",
    name: "LEGO Classic Büyük Yaratıcı Tuğla Kutusu 11025",
    image: "https://picsum.photos/seed/legoclassic/400/400",
    price: 899,
    originalPrice: 1299,
    discount: 31,
    shop: "LEGO Resmi Mağaza",
    sold: 4512,
    rating: 4.9,
    ratingCount: 8923,
    category: "anne-bebek",
    brand: "lego",
    badge: "ÇOK SEVILEN",
    description:
      "1500 parça ve 33 farklı renkte tuğla içeren bu set, 4-99 yaş arası herkes için sınırsız yaratıcılık imkanı sunar.",
    stock: 234,
    variants: [
      { name: "Yaş", options: ["4+", "6+"] },
    ],
    isFlash: true,
  },
  {
    id: "b3",
    name: "Mamas & Papas Orchard Oyun Parkı ve Beşik",
    image: "https://picsum.photos/seed/mamaspark/400/400",
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    shop: "Mamas & Papas Türkiye",
    sold: 892,
    rating: 4.7,
    ratingCount: 1234,
    category: "anne-bebek",
    brand: "mamaspapas",
    description:
      "Beşik, oyun parkı ve sallanabilir özelliğiyle 3'ü bir arada çok fonksiyonlu ürün. 0-2 yaş için idealdir.",
    stock: 34,
    variants: [
      { name: "Renk", options: ["Beyaz", "Gri", "Mavi", "Pembe"] },
    ],
  },

  // ── GIDA & MARKET ──────────────────────────────────────────
  {
    id: "fd1",
    name: "Nespresso Vertuo Pop+ Kahve Makinesi + 30 Kapsül",
    image: "https://picsum.photos/seed/nespresso/400/400",
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    shop: "Nespresso Türkiye",
    sold: 1892,
    rating: 4.7,
    ratingCount: 3201,
    category: "gida",
    brand: "nespresso",
    description:
      "Barcode tanıma teknolojisi ile otomatik doz ayarlı Vertuo sistemi, espresso'dan Gran Lungo'ya beş farklı boyut sunar. 30 saniyede hazır.",
    stock: 89,
    variants: [
      { name: "Renk", options: ["Siyah", "Kırmızı", "Mavi", "Beyaz"] },
    ],
  },
  {
    id: "fd2",
    name: "Doğadan Organik Çiçek Balı 850g",
    image: "https://picsum.photos/seed/dogadanbal/400/400",
    price: 349,
    originalPrice: 499,
    discount: 30,
    shop: "Doğadan Organik",
    sold: 12341,
    rating: 4.9,
    ratingCount: 23412,
    category: "gida",
    brand: "dogadan",
    badge: "ORGANİK SERTİFİKALI",
    description:
      "Organik sertifikalı, işlenmemiş ham bal. Yüksek antioksidan içeriği ve doğal enzimler korunmuş. Soğuk süzme yöntemiyle üretilmiştir.",
    stock: 567,
    isFlash: true,
  },
  {
    id: "fd3",
    name: "Myprotein Impact Whey Protein 5kg - Çikolata",
    image: "https://picsum.photos/seed/myprotein/400/400",
    price: 2999,
    originalPrice: 3999,
    discount: 25,
    shop: "Myprotein Türkiye",
    sold: 5423,
    rating: 4.7,
    ratingCount: 8923,
    category: "gida",
    brand: "myprotein",
    description:
      "Servis başına 21g protein, 100 servis. Yüksek kaliteli Whey Konsantrat ve amino asit profiliyle kas gelişimini destekler.",
    stock: 234,
    variants: [
      { name: "Tat", options: ["Çikolata", "Vanilya", "Çilek", "Cookies & Cream", "Doğal"] },
    ],
  },
];

export const BRANDS: Record<string, { name: string; description: string; banner?: string }> = {
  apple: { name: "Apple", description: "Teknolojinin en ikonik markası. iPhone, Mac, iPad ve daha fazlası.", banner: "https://picsum.photos/seed/applebanner/1200/300" },
  samsung: { name: "Samsung", description: "Galaxy serisi, OLED TV'ler ve ev elektroniğinin öncüsü.", banner: "https://picsum.photos/seed/samsungbanner/1200/300" },
  sony: { name: "Sony", description: "PlayStation, kulaklık ve profesyonel ses sistemleri.", banner: "https://picsum.photos/seed/sonybanner/1200/300" },
  nike: { name: "Nike", description: "Spor ayakkabı, giyim ve aksesuar dünyasının lideri.", banner: "https://picsum.photos/seed/nikebanner/1200/300" },
  adidas: { name: "Adidas", description: "Spor ve lifestyle'ın buluştuğu ikonik marka.", banner: "https://picsum.photos/seed/adidasbanner/1200/300" },
  zara: { name: "Zara", description: "Güncel trendleri uygun fiyatla sunan Inditex'in moda markası.", banner: "https://picsum.photos/seed/zarabanner/1200/300" },
  hm: { name: "H&M", description: "Fast-fashion'da sürdürülebilirliği önceleyen global marka.", banner: "https://picsum.photos/seed/hmbanner/1200/300" },
  mango: { name: "Mango", description: "Akdeniz estetiği ve modern kadın modasının temsilcisi.", banner: "https://picsum.photos/seed/mangobanner/1200/300" },
  levis: { name: "Levi's", description: "1853'ten beri denim kültürünün simgesi.", banner: "https://picsum.photos/seed/levisbanner/1200/300" },
  dyson: { name: "Dyson", description: "Mühendislik mucizesi ev aletleri ve saç bakım cihazları.", banner: "https://picsum.photos/seed/dysonbanner/1200/300" },
  philips: { name: "Philips", description: "Akıllı ev çözümleri ve sağlık teknolojilerinin öncüsü.", banner: "https://picsum.photos/seed/philipsbanner/1200/300" },
  delonghi: { name: "De'Longhi", description: "İtalyan kalitesinde kahve makineleri ve mutfak aletleri.", banner: "https://picsum.photos/seed/delonghiban/1200/300" },
  lego: { name: "LEGO", description: "Yaratıcılığı ödüllendiren Danimarkalı oyuncak devi.", banner: "https://picsum.photos/seed/legobanner/1200/300" },
  cerave: { name: "CeraVe", description: "Dermatolog onaylı medikal cilt bakım ürünleri.", banner: "https://picsum.photos/seed/ceravebanner/1200/300" },
  dior: { name: "Dior", description: "Fransız lüks modasının simgesi. Haute couture ve güzellik.", banner: "https://picsum.photos/seed/diorbanner/1200/300" },
};

export function getProductsByCategory(category: string): Product[] {
  return ALL_PRODUCTS.filter((p) => p.category === category);
}

export function getProductsByBrand(brand: string): Product[] {
  return ALL_PRODUCTS.filter((p) => p.brand === brand);
}

export function getProductById(id: string): Product | undefined {
  return ALL_PRODUCTS.find((p) => p.id === id);
}

export function getRelatedProducts(product: Product, limit = 4): Product[] {
  return ALL_PRODUCTS.filter(
    (p) => p.id !== product.id && (p.category === product.category || p.brand === product.brand)
  ).slice(0, limit);
}
